services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
      - data_storage:${STORAGE_DIR:-/data/storage}
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: >
      sh -c "uvicorn backend.app.main:app --host ${API_HOST:-0.0.0.0} --port ${API_PORT:-8000}"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
      - data_storage:${STORAGE_DIR:-/data/storage}
    depends_on:
      - redis
    command: >
      sh -c "celery -A backend.app.workers.tasks.celery worker --loglevel=INFO"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  data_storage:
